# Generated by Django 3.2.25 on 2024-11-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options'),
        ('issues', '0009_auto_20241112_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('high', 'high'), ('low', 'low'), ('critical', 'critical'), ('medium', 'medium')], default='low', max_length=10),
        ),
    ]
