# Generated by Django 3.2.25 on 2024-11-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_auto_20241112_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('critical', 'critical'), ('low', 'low'), ('high', 'high'), ('medium', 'medium')], default='low', max_length=10),
        ),
    ]
