# Generated by Django 3.2.25 on 2024-11-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_alter_issue_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='console_error',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue_project',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='repeatable',
        ),
    ]
