# Generated by Django 3.2.25 on 2024-11-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0018_alter_issue_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Critical', 'critical'), ('Medium', 'medium'), ('Low', 'low'), ('High', 'high')], default='low', max_length=10),
        ),
    ]
