# Generated by Django 3.2.25 on 2024-11-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0067_alter_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Low', 'low'), ('Medium', 'medium'), ('High', 'high'), ('Critical', 'critical')], default='low', max_length=10),
        ),
    ]
