# Generated by Django 3.2.25 on 2024-11-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_projecturl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_on']},
        ),
    ]
