# Generated by Django 3.2.25 on 2024-11-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='githubtURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
